# Known requirements per distro, please expand if you encounter breakage
known_distros:
  - CentOS
  - Fedora
  - Ubuntu
  - Debian
  - Red Hat Enterprise Linux
  - Arch Linux

debian_deps:
  - git
  - iptables-persistent
  - libssl
  - iproute
  - ebtables
  - ipset
  - logrotate

centos_deps:
  - iptables-services
  - git
  - openssl
  - iproute
  - ebtables
  - ipset
  - logrotate

ubuntu_deps:
  - git
  - iptables-persistent
  - libssl-dev
  - libsqlite3-dev
  - iproute2
  - ipset
  - ebtables
  - logrotate

fedora_deps:
  - iptables-services
  - git
  - openssl
  - iproute
  - ebtables
  - ipset
  - logrotate

arch_deps:
  - git
  - openssl
  - iproute
  - ebtables
  - ipset
  - logrotate
