---

- name: Setup Natting rules
  shell: 'firewall-cmd --direct --permanent --add-rule ipv4 nat POSTROUTING 0 -o {{external_nic}} -j MASQUERADE'
  become: true

- shell: 'firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i {{internal_nic}} -o {{external_nic}} -j ACCEPT'
  become: true

- shell: 'firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i {{external_nic}} -o {{internal_nic}} -m state --state RELATED,ESTABLISHED -j ACCEPT'
  become: true

- shell: 'firewall-cmd --reload'
  become: true

- name: Set ipv4 forwarding to on
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
    state: present
  become: true
  register: sysctl

- name: Reload sysctl
  shell: "sysctl -p"
  become: true
  when: sysctl is changed

- name: Ensure iptables runs on startup
  service:
    name: firewalld
    state: started
    enabled: yes
  become: true
