---
# Sets up wireguard to run at boot with a given config

- name: Make wireguard config dir
  file:
    path: /etc/wireguard
    state: directory
  become: true

- name: Template Gateway wireguard config
  template:
    src: wgBridge.conf.j2
    dest: /etc/wireguard/wgBridge-{{item.port}}.conf
    owner: root
    mode: 500
  become: true
  with_items: "{{gateways}}"

- name: Template wireguard config
  template:
    src: wgInternal.conf.j2
    dest: /etc/wireguard/wgInternal.conf
    owner: root
    mode: 500
  become: true

- name: Open Internal port UDP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "{{wg_port}}/udp"
  become: true

- name: Open Internal port TCP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "{{wg_port}}/tcp"
  become: true

- name: Open Gateway port UDP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "{{item.port}}/udp"
  become: true
  with_items: "{{gateways}}"

- name: Open Gateway port TCP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "{{item.port}}/tcp"
  become: true
  with_items: "{{gateways}}"

- name: Open Babeld port TCP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "6696/tcp"
  become: true

- name: Open Babeld port UDP
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    port: "6696/udp"
  become: true

- name: Template scripts
  template:
    src: "{{item}}"
    dest: "/bin/{{item}}"
    mode: 744
  become: true
  with_items:
    - start-wg
    - stop-wg
    - update-wg

- name: Template WireGuard service file
  template:
    src: wireguard.service.j2
    dest: /etc/systemd/system/wireguard.service
  become: true

- name: Set Wireguard service to run on startup
  systemd:
    daemon_reload: yes
    name: wireguard
    state: started
    enabled: yes
  become: true

- name: Template Babel configuration
  template:
    src: babeld.conf.j2
    dest: /etc/babeld.conf
  become: true
