---
# Lock down the rest of the system and handle various potential attacks

- name: Allow already open connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Open ssh port
  iptables:
    chain: INPUT
    destination_port: "22"
    protocol: "tcp"
    ip_version: "{{item}}"
    jump: ACCEPT
    ctstate: NEW
  become: true
  with_items:
    - ipv4
    - ipv6

- name: Remove default drop rules
  iptables:
    chain: INPUT
    jump: REJECT
    reject_with: "icmp6-adm-prohibited"
    ip_version: ipv6
    state: absent
  become: true

- name: Remove default drop rules
  iptables:
    chain: INPUT
    jump: REJECT
    reject_with: "icmp-host-prohibited"
    ip_version: ipv4
    state: absent
  become: true

- name: Lock down input chain
  iptables:
    chain: INPUT
    policy: DROP
  become: true

## TODO block ICMP spam attacks, DDOS style attacks etc https://javapipe.com/ddos/blog/iptables-ddos-protection/

- name: save iptables rules
  shell: "service {{item}} save"
  become: true
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' 

- name: save iptables rules
  shell: "{{item}}"
  become: true
  with_items:
    - "iptables-save > /etc/iptables/rules.v4"
    - "ip6tables-save > /etc/iptables/rules.v6"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

