---

- name: Enable Debian Unstable
  repo: deb http://deb.debian.org/debian/ unstable main
    state: present
  become: true

- name: Set unstable packages as low priority
  blockinfile:
    path: /etc/apt/preferences.d/limit-unstable
    create: true
    block: |
      Package: *
      Pin: release a=unstable
      Pin-Priority: 150
  become: true

- name: Install wireguard
  apt:
    name: "{{item}}{{wireguard_version}}"
    update_cache: yes
  become: true 
  with_items:
    - wireguard-dkms
    - wireguard-tools
